### PR TITLE
meta.yaml with openblas instead of MKL

### PR DESCRIPTION
**Pull request by atztogo**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This PR is for 

* Replacing MKL by openblas
* `extra_link_args = -lgomp` is added to `site.cfg` for `[linux]`
* Run test to check compiled phono3py
* Avoid running test for `[osx]` with py37 because the test fails

### CODE REVIEW

**Comment by atztogo** [comment]
@jan-janssen. The phono3py package made by `meta.yaml` in PR #31 did not work in run time due to

```
ImportError: /home/togo/.miniconda/envs/phono3py/lib/python3.9/site-packages/phono3py/_phono3py.cpython-39-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num
```

To provide conda-forge package of phono3py, do I need another release of phono3py with different version number?

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Somehow it is not linking to openblas:
```
WARNING (phono3py): run-exports library package conda-forge::libcblas-3.8.0-11_h86c2bf4_netlib in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (phono3py): interpreter (Python) package conda-forge::python-3.10.4-h2660328_0_cpython in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (phono3py): run-exports library package conda-forge::numpy-1.22.3-py310h45f3432_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (phono3py): run-exports library package conda-forge::libblas-3.8.0-11_h86c2bf4_netlib in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (phono3py): dso library package conda-forge::libgfortran5-11.2.0-h5c6108e_15 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

**Comment by atztogo** [comment]
On numpy in `requirements/run`
https://numpy.org/doc/stable/user/depending_on_numpy.html

About the WARNINGs, the similar warnings are in the [phonopy build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=489188&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642). So what I wrote above is not true. I have no idea.

I hope `meta.yaml`'s requirements section is cleaner.

**Review by jan-janssen — APPROVED** [review]
Looks good to me 
https://conda-forge.org/docs/maintainer/knowledge_base.html#blas

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by atztogo** [comment]
Thank you very much @jan-janssen!

**Pull request merged**
