### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by atztogo**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by atztogo** [comment]
@conda-forge-admin, please rerender

**Comment by atztogo** [comment]
#36 fails by [numpy issue](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=564523&view=logs&jobId=253ea3ec-a032-5a61-0d20-dbf0bb326fc2&j=253ea3ec-a032-5a61-0d20-dbf0bb326fc2&t=8f279e6b-1d24-5e23-4618-cb474b6bf3b9). I am not very sure if what I do here is correct or not. But after rerendering, the file names are changed to contain "numpy" in them like [phonopy-feedstock](https://github.com/conda-forge/phonopy-feedstock/tree/main/.ci_support), which I guess it's a good sign.
Could @jan-janssen review this PR if this is a correct direction?

**Comment by jochym** [comment]
@conda-forge-admin, please rerender

**Comment by jochym** [comment]
@atztogo I think this is a correct direction. Let us check after rerender and commit. Please make sure the tests are actually running.

**Comment by jochym** [comment]
@conda-forge-admin, please rerender

**Comment by atztogo** [comment]
Thanks @jochym.

> Please make sure the tests are actually running.

Yes, tests ran and finished OK.

**Pull request merged**
